### ISSUE TITLE
☂️ Registry Integration

### ISSUE THREAD

**Issue by matifali** [coder/coder#10664]
# Coder Registry Integration

This umbrella issue tracks the progress of the [**Coder Registry Integration**](https://github.com/coder/coder/milestone/28) milestone and breaks the work into individual issues. For more details, please take a look at the individual issues. 

### Must have

- [x] #10639 
- [x] #10640 
- [ ] #10991
- [x] #10641 
- [x] #10682
- [x] #10684

### Should have

- [x] #10642 
- [ ] #10990 
- [ ] #10643 
- [x] #10651
- [ ] #11645
- [x] #10653
- [x] #8449 
- [ ] https://github.com/coder/modules/issues/93
	- [ ] #10352
	
### Must have

- [x] https://github.com/coder/registry.coder.com/issues/7
	- [x] https://github.com/coder/modules/issues/70  
- [x] https://github.com/coder/registry.coder.com/issues/4
- [x] https://github.com/coder/registry.coder.com/issues/3
- [x] https://github.com/coder/registry.coder.com/issues/2

### Should have

- [ ] https://github.com/coder/registry.coder.com/issues/6
- [x] https://github.com/coder/registry.coder.com/issues/5

### Nice to have
- [x] https://github.com/coder/registry.coder.com/issues/8

**Comment by bpmct** [comment]
We're going to revisit the registry in more detail later this year. We'll reference that list, but this isn't super actionable or accurate right now
