### ISSUE TITLE
☂️ Improve the user experience on the CLI

### ISSUE THREAD

**Issue by mafredri** [coder/coder#10759]
This is an umbrella issue tracking issues with the user experience on the CLI.

- [x] https://github.com/coder/coder/issues/10760
- [x] https://github.com/coder/coder/issues/10761
- [ ] https://github.com/coder/serpent/issues/3
- [x] https://github.com/coder/coder/issues/9318
- [x] https://github.com/coder/coder/issues/10281
- [x] https://github.com/coder/coder/issues/8107
- [x] https://github.com/coder/coder/issues/10762
- [x] https://github.com/coder/coder/issues/2154
- [x] coder/coder#10767
- [x] coder/coder#6424
- [x] coder/coder#7816 
- [x] coder/coder#11006
- [x] coder/coder#11002
- [x] coder/coder#11003
- [x] coder/coder#10925
- [ ] coder/coder#7524
- [x] coder/coder#11348
- [ ] coder/coder#11297
- [ ] coder/coder#10626
- [x] coder/coder#9551
- [x] coder/coder#11410
- [x] coder/coder#9329
- [x] coder/coder#11328
- [ ] coder/coder#11505
- [ ] coder/coder#6235
- [x] coder/coder#10357

Nice to haves:
- [ ] coder/coder#7524
- [x] coder/coder#11348
- [ ] coder/coder#6712 
- [x] coder/coder#2744
- [ ] coder/coder#11004
- [ ] coder/coder#11298 (CLI + Web)

**Comment by matifali** [comment]
Could we also add #9318 to the list?

**Comment by mafredri** [comment]
@matifali thanks, added. Added https://github.com/coder/coder/issues/10281 for good measure too.

**Comment by kylecarbs** [comment]
Most of these are closed and we're stopping gigaissues. Awesome that so many have been closed :')
