### ISSUE TITLE
☂️ fix Jest tech debt

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#11418]
It should be easy for newcomers to add Jest tests to our FE codebase, so we should address the below issues (which may warrant their own tickets:

- [ ] fix the `act` warnings we get when running our test suite
- [ ] get rid of any jest 'it exists' tests which are duplicative since we have storybook testing for each component
- [ ] clean up `entities.ts`: delete any unnecessary mocks in favor of using the spread operator in individual tests if we need specific fields tweaked

**Comment by kylecarbs** [comment]
@Kira-Pilot closing unless we're planning to do this soon. Please reopen if you feel we should!
