### ISSUE TITLE
workspace deadline warning lacks specific time and reason for shutdown 

### ISSUE THREAD

**Issue by stirby** [coder/coder#11694]
The current workspace shutdown warning doesn't display clear enough information for users. It could be specifically improved with adding reasons for imminent shutdown and more granular deadline display.

</br>

### pseudo-precise shutdown timer

With the current implementation of activityBump from #10704, a static display of workspace shutdown isn't quite suitable. When a user is active in their workspace, a message like the following would be misleading:

<img width="387" alt="autostop_message_1" src="https://github.com/coder/coder/assets/58410745/88b0ecea-3541-4109-8b7b-edd0517250e5">

Since their workspace shutdown deadline would actually be continuously bumping up while they are using it. To remedy this, we could simulate a second-level timer counting up while the user is in their workspace when any TTL configuration is enabled. 

From my understanding, 

</br>

### Reason for workspace shutdown

There's also no way for a user to understand why there workspace will shutdown in the displayed interval. A workspace slated for shutdown from a configured Autostop Requirement has greater implication than that from a lack of activity. 

<img width="587" alt="Screenshot 2024-01-18 at 4 06 31 PM" src="https://github.com/coder/coder/assets/58410745/11885d9e-ff3f-4830-87e0-3dcc88f1c916">

### Tasks
- [x] More precise time display on deadline
- [ ] Time to shutdown increments with activity bump  
- [x] Textual reason for shutdown (Autostop Requirement, Inactivity, quiet hours)
- [x] Whether the shutdown is being enforced by template or workspace configuration
- [ ] ~docs~

### Examples

I'll obviously yield to FE here...

> 1 day, 17:16:12 until workspace shutdown by `Autostop Requirement` Template Policy

> Workspace will shutdown in `17 hours`, `19 minutes` (Autostop Requirement)

> Workspace will shutdown in `17 hours`, `19 minutes` (Inactivity Timer (see [#11690](https://github.com/coder/coder/issues/11690)))
