### ISSUE TITLE
Sharable ports: e2e flow checklist

### ISSUE THREAD

**Issue by stirby** [coder/coder#12335]
**Blocked by** https://github.com/coder/coder/issues/13163

List of flows expected by the customer, will hopefully guide focus for test coverage.

Sharable Ports umbrella: https://github.com/coder/coder/issues/11486

### Basic flows
- [ ] Sharing a port
  - [ ] Ports can be shared in the UI
  - [ ] Ports can be shared using an API endpoint
  - [ ] Ports can be shared using the CLI
    `coder share-port my_workspace —port 3333 —sharing_level “Public”`
- [ ] Users can change share level via UI 
- [ ] Users can remove a shared port
- [ ] Users can share `coder_app`s by manually entering their port number in UI, or through CLI

### Admin control
- [ ] When max sharing level is reduced, 
  - [ ] all shared ports in higher sharing level are reduced to new maximum
  - [ ] if `owner`, they become unpinned
- [ ] admins can change share level in workspaces
- [ ] admins can access ports in owner scope (forwarded ports)
