### ISSUE TITLE
Epic: Bundled Observability

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#12797]
This is the holding issue for the set of improvements we want to make based on [RFC: Bundled Observability](https://github.com/coder/coder/discussions/12793).

**Goal**: produce a separate Helm chart which can be installed with one script to observe a Coder deployment. Each sub-chart should contain at least one dashboard, alert, and runbook to cover its own functional requirements (i.e. the Grafana installation should have a dashboard, alert, runbook to enable operators to observe it). The Coder deployment should be covered by several dashboards, alerts & runbooks, and we should collect all telemetry signals as applicable (metrics, logs, traces, profiles).

**Initial Requirements**:

- [ ] Deploy the LGTM stack in our internal environment to setup & configure (https://github.com/coder/dogfood/issues/43)
- Create a new Helm chart for bundled observability
  - [ ] Add & configure Grafana chart
  - [ ] Add & configure Prometheus/Alertmanager chart, add Grafana datasource
    - [ ] Enable configureable notification routes _(maybe offer Coder deployment as notification target, display alerts in UI?)_
  - [ ] Add & configure Loki chart, add Grafana datasource
    - [ ] Enable configureable notification routes _(maybe offer Coder deployment as notification target, display alerts in UI?)_
  - [ ] Publish observability Helm chart
  - [ ] Update documentation
  - [ ] Write blogpost
- Create observability resources
  - [ ] Create dashboards covering major Coder architectural components
  - [ ] Vendor in or create dashboards covering Kubernetes and Go runtime
  - [ ] Create alerts & runbooks covering major Coder architectural components, deployment environment
  - [ ] Update documentation
  - [ ] Write blogpost

**Eventual Requirements**:
- [ ] Add & configure profiling chart, add Grafana datasource
- [ ] Add & configure tracing chart, add Grafana datasource

**Comment by dannykopping** [comment]
Adhoc task list:

## General
- [ ] handle unmanaged resources (i.e. resources created but subsequently not managed by helm)
- [ ] find a way to include common patches & other configs in local/prod kustomizations

## Prometheus / Alertmanager
- [ ] ignore container ports discovered with kubernetes_sd_config which do not expose metrics (i.e. Loki's gRPC ports) (use `extraScrapeConfigs`)
- [ ] alert source addresses should use FQDN (prometheus-server.monitoring.svc.cluster.local)
- [ ] include runbook link via label
- [ ] test out slack receiver
- [ ] optimise labels and unify with loki labels

## Grafana
- [ ] dashboards persistence

## Loki
- [ ] optimise labels
- [ ] scrape logs from all pods
- [ ] add cluster label to loki metrics

**Comment by bpmct** [comment]
Can we add this as a step in our Kubernetes install docs as Recommended, but optional? https://coder.com/docs/v2/latest/install/kubernetes
