### ISSUE TITLE
☂️ Workspace Activity Refactor

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#13146]
Collection of issues related to the Unified Workspace Statistics and Activity Detection RFC: https://www.notion.so/coderhq/Unified-Workspace-Statistics-and-Activity-Detection-11cdaf2b55bc493382ecfc302ca3d6f9

Subject to change as the RFC is finalized. 

`meta`:
- [x] https://github.com/coder/coder/issues/13147
- [x] https://github.com/coder/coder/issues/13158
- [x] https://github.com/coder/coder/issues/13159

`coderd/workspaceapps`:
- [x] https://github.com/coder/coder/issues/13148
- [x] https://github.com/coder/coder/issues/13149
- [x] https://github.com/coder/coder/issues/13150
- [x] https://github.com/coder/coder/issues/13151

`coderd/agentapi`:
- [x] https://github.com/coder/coder/issues/13152

`coderd`:
- [x] https://github.com/coder/coder/issues/13153
- [x] https://github.com/coder/coder/issues/13154
- [x] https://github.com/coder/coder/issues/13155

`cli`:
- [x] https://github.com/coder/coder/issues/13156
- [x] https://github.com/coder/coder/issues/13157

**Comment by f0ssel** [comment]
Closing in favor of using the milestone https://github.com/coder/coder/milestone/34
