### ISSUE TITLE
Epic: Notifications Subsystem

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#13227]
We will be building a notification subsystem into Coder which will facilitate the sending of manual & automatic messages.

We're going to start off by building a low-fidelity vertical slice of the functionality to validate a few ideas. This version will not be merged into `main` necessarily; it's more to smoke out any flaws / oversights in the design.

### Initial spike
- [ ] create terraform resource referencing `coder_agent` metadata keys for rule-based evaluations
- [ ] create database entities for notification "templates", "instances", and "conditions"
- [ ] create basic evaluation engine to create notification "instances" from "template" once coder_agent metadata value crosses threshold (or some other condition becomes true)
- [ ] create and run _n_ in-process notification consumers (reading from the database queue)
  - start with _n=1_ initially, but stretch goal to have _n>1_ working (to sniff out lock contention problems)
- [ ] implement routing of notification instances to the matching workspace(s)
- [ ] enable basic notification display in Coder UI
- [ ] (stretch) enable notification display in CLI
- [ ] (stretch) enable notification display in VSCode
- [ ] (stretch) enable notification display in JetBrains

**Comment by dannykopping** [comment]
We're rescoping this project to deal with system-generated notifications instead.
I will link to the new milestone once created.

**Comment by dannykopping** [comment]
https://github.com/coder/coder/milestone/35
