### ISSUE TITLE
Refactor external APIs to be compatible with new workspace activity tracking

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#13281]
Once we update how the internal APIs handle tracking of user activity we must update things like the CLI and jetbrains plugins to be compatible with the new flows. This will ensure users will continue to see accurate data from these external sources. 

- [ ] Modify `/usage` endpoint to accept a payload and call `StatsCollector.Collect()`, returning a `SessionID` if required
- [ ] Update CLI commands (`coder ssh`, etc.) to periodically send a payload to `/usage`
- [ ] Include an option to skip tracking
- [ ] Update coder-jetbrains plugin to periodically send payloads to `/usage`
    - Ensure that periodic background activity does not send unwanted activity bumps
