### ISSUE TITLE
Create `notifications` package

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#13331]
- [x] Implement operations for entities (see also https://github.com/coder/coder/issues/13329)
  - [ ] ~Templates~
    - [ ] ~Create~
    - [ ] ~Update~
    - [ ] ~Prevent manual deletion~
  - [x] Messages
    - [x] Enqueue
    - [x] Dequeue
    - [x] Update
    - [x] Purge old
    - [x] Deduplication
  - [ ] ~Preferences~
    - [ ] ~Create~
    - [ ] ~Update~
- [x] Template Renderer (see also https://github.com/coder/coder/issues/13328)
  - [x] Implement HTML renderer which takes `notifications_messages` labels as input
  - [x] Implement text renderer which takes `notifications_messages` labels as input
- [x] Basic REST API
  - [x] Pause/resume all notifications
    - [x] Add CLI command
  - [ ] ~CRUD `notification_preferences`~
- [x] Implement receivers
  - [x] Create retry mechanism
  - [x] SMTP
    - [x] Handle successful delivery
    - [x] Handle unsuccessful delivery (retries)
    - [x] Handle exceeded retries
  - [x] Webhook
    - [x] Handle successful delivery
    - [x] Handle unsuccessful delivery (retries)
    - [x] Handle exceeded retries
- [x] Amend `dbpurge` to delete old `notification_messages` after a configurable number of days
- [x] Observability of key operations
  - [ ] Notifications sent (by receiver, notification_template)
  - [ ] Notifications failed (by receiver, notification_template)
  - [ ] Notifications retried (by receiver, notification_template)
  - [ ] Notifications paused
  - [ ] Notifications purged
  - [ ] Queue operations
    - [ ] Enqueue time (delta between start of operation and accepted into db)
    - [ ] Dequeue time (delta between enqueued and dequeued)
  - [ ] Receiver operations
    - [ ] Send time (response time from server, by response status)

**Comment by dannykopping** [comment]
Ejecting from sprint XVI; more narrowly scoping deliverables
