### ISSUE TITLE
☂️ Restructure our docs

### ISSUE THREAD

**Issue by bpmct** [coder/coder#13434]
We're working on a new information hierarchy for coder.com/docs with a few goals in mind:

1. **Quickstart**: Our current structure reads like a reference, which can be great for recalling information but makes it difficult for a new reader who is unfamiliar with Coder (or CDEs) to learn the basics, even by deploying.
2. **Developer Guides**: Clear hub for for end users on interacting with Coder including creating workspaces, connecting, scheduling, and personalizing
3. **Administration Hub**: The Administration page should serve as a clear path to administering Coder, including tutorials with best practices, docs on administrative features, and reference architectures and use cases.

You can see our progress in the [restructure-new](https://github.com/coder/coder/tree/restructure-new/docs) branch or even on our docs site: https://coder.com/docs/@restructure-new

## Coder.com Changes Required

- [x] Fix our search weights 
- [x] Add autogenerated `og:image` for each page
- [x] Improve loading speed 
- [x] Move sidebar to the top right
- [x] Change URL structure
- [x] Add support for sub icons
- [x] Add border around images for better contrast between Coder dashboard screenshots and background
- [x] Design a landing page for the home page that links to the various sections

## Docs

- [x] About
- [x] Getting Started
  - [x] Landing Page
  - [x] Coder Tour
    - [x] Coder installation on docker
    - [x] Configuring the first template 
    - [x] Creating and connecting to a workspace
    - [x] Template modification 
  - [x] Screenshots
- [x] Install
  - [x] Landing Page
    - [x] Reduction of clutter from previous landing
    - [x] Tabs and children nesting
  - [x] Coder CLI
  - [x] Docker
  - [x] Kubernetes
    - [x] Migrate auto versioning
    - [x] Correct CLI flags with new PR method 
  - [x] OpenShift
  - [x] Other Cloud Providers
  - [x] Unofficial Methods
    - [x] EC2
    - [x] GCP compute engine
    - [x] Azure
    - [x] Any other
  - [x] ~Post-installation steps~ (part of control plane configuration)
	- [x] ~Reverse proxy (Setup SSL certs)~
	- [x] ~Docker socket permission (explain for k8s, docker-compose and system-service) installations~
- [x] User guides
  - [x] Landing Page
  - [x] Access Workspaces
    - [x] VS Code 
    - [x] JetBrains
    - [x] Remote Desktop (broken)
      - [x] Improvements from https://github.com/coder/coder/issues/13003
    - [x] Emacs TRAMP
    - [x] Port Forwarding
    - [x] Web IDEs
  - [x] Workspace Scheduling
  - [x] Dotfiles
    - [x] From a template
    - [x] Personalize script 
- [x] Administration
  - [x] Control plane access (previously [admin/configure.md](https://coder.com/docs/admin/configure))
  	- [x] Add external auth 
  - [x] Infrastructure
    - [x] Landing Page
    - [x] Architecture Diagram
    - [x] Validated Architectures (from @ericpaulsen + 1000-3000 user scale test)
  	- [x] Scale Testing
  	- [x] Scale Testing Utilities 
  - [x] User Management (Does this replace the existing `admin/auth` page)
    - [x] Landing Page
    - [x] OIDC
    - [x] GitHub
    - [x] Password Authentication
    - [x] Headless Authentication
    - [x] Groups & Roles
    - [x] Sessions & API Tokens
      - ~[x] Check if https://github.com/coder/coder/pull/13424 is merged & adjust~
  - [x] Templates
    - [x] Landing Page
    - [x] Creating Templates
    - [x] Managing Templates
    	- [x] Image management
    	- [x] Devcontainers(`envbuilder`)
    	- [x] Change management
    - [x] Extending Templates
    	- [x] Landing Page
	        - [x] Agents
	        	- [x] Multiple Agents 
	        - [x] Resource Persistence
	        - [x] Variables
	        - [x] Parameters
	        - [x] Resource Metadata
	        - [x] Agent Metadata
	        - [x] Ordering
	  	- [x] Web IDEs
	  	- [x] External Authentication
    - [x] Template Permissions
      - [x] Add template policies
    - [x] Create corresponding tutorials
    - [x] Troubleshooting Templates
    - [x] Protecting Resources
  - [x] Provisioners
  - [x] Notifications
  - [x] Integrations
    - [x] Landing page
      - [x] Add links to children pages via landing page (ideally via a widget)
    - [x] Prometheus
    - [x] `coder-logstream-kube`
    - [x] Additional Kubernetes clusters
    - [x] JFrog (Artifactory and XRay)
    - [x] Hashicorp Vault
    - [x] Island
  - [x] Workspaces
    - [x] Landing Page
      - [x] Bulk operations
      - [x] Management and filtering 
      - [x] Update policies stub
    - [x] Workspace Lifecycle
    - [x] Dormancy Cleanup
    - [x] Workspace-level scheduling
    - [x] Workspace Tags
  - [x] Networking
    - [x] Port forwarding
    - [x] STUN & NAT 
    - [x] Decision on [Networking Performance Doc](https://www.notion.so/coderhq/Networking-Performance-Doc-8c891ebf1dbf4775a4ddfee3e55b602e?pvs=4)
      Waiting until merge to add more performance benchmarking, blog post mention is sufficient
  - [x] Monitoring
    - [x] Logs
    - [x] Metrics
    - [x] Observibility Dashboard
    - [x] Support Bundle
    - [x] Health Check
      - [x] Add screenshot
  - [x] Security
    - [x] Audit logs
    - [x] Secrets
    - [x] Security disclosures
  - [x] Tutorials
    - [x] Copy everything from tutorials in `guides/`
    - [x] ~Add VM support for `offline` docs or mention that the guide is K8s only~
  - [x] FAQ 
    - [x] We want to keep this since we frequently link, or move it over
  - [x] Docs to consider
    - [x] Coder Premium (this needs a home somewhere)
      - [x] https://github.com/coder/coder/issues/12973
- [x] Reference
  - [x] Landing Page
  - [x] CLI
  - [x] API 

## Chores

- [x] Ensure `make gen` writes to the new docs locations
  - [x] CLI
  - [x] REST API
  - [x] Prometheus Metrics
  - [x] Version rewrites
  - [x] Audit logs
- [x] Check for (and address) any `TODO`s
- [x] Ensure that all sections either have A) icon for each sub page or B) no icons for the section
- [x] Check for (and address) any broken images
- [x] Add redirects from old URLs to new docs pages/sections with over 5 views per month
  - [x] Click through all pages in previous docs and ensure that they either A) have a new home in new docs or B) are good to be deleted/redirected to a new place. 
  - [ ] Merge https://github.com/coder/coder.com/pull/652
- [x] Modify in-product docs links to link to the new location as well
- [x] Check for broken links
- [x] ~Switch link checker to https://github.com/UmbrellaDocs/action-linkspector~
- [x] https://github.com/coder/coder.com/issues/508
  - [x] "Recent updates" gallery
  - [x] Main hero element
  - [x] Ecosystem gallery
- [x] Migrate updates to main into restructure branch
  - [x] Workspace tags
  - [x] ~Releases calendar~

**Comment by matifali** [comment]
The new docs look way cleaner. 🚀

**Comment by matifali** [comment]
We should alao migrate our docs link checker to https://github.com/UmbrellaDocs/action-linkspector
The current is going to be deprecated in favor of this.

**Comment by bpmct** [comment]
Added validated architectures @ericpaulsen https://coder.com/docs/@restructure/admin/infrastructure/validated-architectures

**Comment by bpmct** [comment]
@stirby what is your rationale about "screenshots" being in getting started? I added it there, but I figured that section would be tutorial oriented. Overall, I'm a bit confused on the difference between about and getting started sections

**Comment by stirby** [comment]
In my eyes, "Getting Started" should be day-zero setup process for those already interested in the product. "About" should be seen by anyone exploring the product, regardless of setup interest. 

I put it under "Getting Started" since I see myself "touring" the product by looking around the UI, then setting it up. 

I assume you'd suggest moving it under "About?" I agree it conceptually fits but I wanted to avoid a subsection there.

**Comment by bpmct** [comment]
I'm kind of stuck on where to put `Provisioners`. I put it under Admin, but it doesn't feel right... Maybe under Admin->Infrastructure or Admin->Templates

**Comment by matifali** [comment]
I would go with infrastructure but will link from groups as it's more useable with groups/teams managing their own compute resources.

**Comment by stirby** [comment]
Seems like we may need a `deployment/` section under administration. 
- configure.md
- Upgrading deployments
- Provisioners

Not sure what the README would look like, maybe talking about scope?

Not a concrete decision, just something to investigate.

**Comment by matifali** [comment]
We may also document the secret management methods we support at https://coder.com/docs/secrets.
- https://registry.coder.com/modules/vault-github
- https://registry.coder.com/modules/hcp-vault-secrets

**Comment by stirby** [comment]
@matifali good call! I think these belong in "integrations" but we should link to them in the secrets doc as children.

**Comment by matifali** [comment]
> We may also document the secret management methods we support at [coder.com/docs/secrets](https://coder.com/docs/secrets).
> 
> * [registry.coder.com/modules/vault-github](https://registry.coder.com/modules/vault-github)
> * [registry.coder.com/modules/hcp-vault-secrets](https://registry.coder.com/modules/hcp-vault-secrets)

This is now complete. I added this under integrations and linked from `admin/secrets`.

**Comment by stirby** [comment]
For the rest of this week:

@stirby 
- RDP Page fixes
- Migrate Scale pages to infrastructure
- Merging Landing Page

@matifali 
- External Authentication
- Image Management 
  - Mentioning Envbuilder, devcontainer spec, envbuilder templates
- Security
- Final tutorials

**Comment by stirby** [comment]
Atif Tasks
- Template Management
  - Copy Change Management under template management
  - Copy Devcontainers file
  - Change "Creating Templates" tabs, rename "Git" to "CI/CD"
- Extending templates: add terraform modules
- Separate IDEs between user guides and 
- Add Post installation steps

Stephen Tasks
- Correct Templates page hierarchy
- Add metrics page
- Decision on security disclosures

**Comment by stirby** [comment]
Tasks

Atif
- [ ] Move "Getting Started" to "About" remove old "About" content
- [ ] Move "Screenshots" under home
- [ ] Move "Tour Coder" under Home
- [ ] Rename "Control Plane" to "setup"
- [ ] Move "Automation" to "Reference"
- [ ] External Authentication under Administration
- [ ] Add icons for all second-level headings

Stephen 
- [ ] Write Landing Pages
- [ ] Metrics Page
- [ ] Move Notifications to Monitoring
- [ ] Icons for User guides

**Comment by stirby** [comment]
Steve's task for 09/11 -> 09/14
- [ ] Add `premium` badges for new pricing plan
- [ ] _likely_ deprecate `enterprise` badges
- [ ] Pricing disambiguation page
- [ ] Add non-prometheus metrics to monitoring/metrics page
  - [ ] Template insisghts
  - [ ] Insights API endpoint https://dev.coder.com/swagger/index.html#/

**Comment by stirby** [comment]
https://github.com/coder/coder/issues/14673

**Comment by stirby** [comment]
We're waiting to return the enterprise feature comparison until we add the coderd licensing options. Then we'll have a "Licensing" section under administration.

- Licensing
  - `README.md` : Explains how to add licenses, license limit
  - `compare.md` : Feature set comparison between OS / Premium

**Comment by bpmct** [comment]
I'll do the licensing stuff this week. What is an ETA looking like, including us adding redirects?

**Comment by matifali** [comment]
Adding redirects requires fixing all dead links and stale images and checking for missing docs. If we can get these completed by end of the week we can add redirects and merge.

**Comment by bpmct** [comment]
Added this checkbox to the tracker above:

- [ ] Modify in-product docs links to link to the new location as well
