### ISSUE TITLE
:open_umbrella: Coder Enterprise features to be compatible with multiple organizations

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#13774]
Enterprise features need upgrades to their configuration and implementation to be compatible with multiple organizations. Each upgrade can be it's own issue with more details/discussion.

- [x] Group sync only works for the default organization. Also sync org membership. https://github.com/coder/coder/issues/14202
- [x] Role sync needs to be expanded to allow assigning organization scoped roles https://github.com/coder/coder/issues/14203
- [x] SCIM assumes the default organization when inserting a new user https://github.com/coder/coder/issues/14204
- [x] Workspace quotas needs to be reviewed. Given they are group synced, the primary work is to ensure the quota buckets do not leak cross-organization https://github.com/coder/coder/issues/14349

As it stands these features have no concept of multiple organizations, and reference the singular "default" organization.
