### ISSUE TITLE
Add auditing to the organization page

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#13913]
We currently audit key user actions and resource creation within our dashboard. As we are introducing the concept of organizations into Coder, we should create an org-scoped audit view so that users can identify changes relevant to a specific org.

~Note that ideally, we would like to de-duplicate audit log views rather than having two (our existing audit log view and the new org-scoped audit log view laid out in this ticket). We will revisit design and find a way to consolidate views after orgs is in experimental.~ We ended up consolidating audit views and the below criteria has been updated.

**Requirements**
- [x]  In our existing audit log page, add organization context to each audit log item, perhaps alongside the IP and OS detail. If space is constrained, consider responsive design in [below comment](https://github.com/coder/coder/issues/13913#issuecomment-2248627918).
- [x] ~In our existing audit log view, ensure that any audit log item (for example, template creation) correctly displays the org in the diff (we should get this for free), e.g. in the below image, `org id` or `org name` should be included *only* if there is an actual diff~ resources cannot move to a different organization
- [x] Move our existing audit log view to `deployment/audit` and update sidebar to reflect new menu item
- [x] Match the design laid out in [the below comment](https://github.com/coder/coder/issues/13913#issuecomment-2248627918)
- [x] Add "Auditing" link under each organization sidebar item that redirects to `deployment/audit` with org filter applied and org query applied.
- [x] Org filter should be editable so users do not have to scroll back down to organizations to filter by a different organization
- [x] Add an 'All Organzations' dropdown filter to the audit log view
- [ ] Add Jest tests for basic functionality
- [x] Add storybooks
- [x] ~Create a separate issue to encapsulate the work required to consolidate our two audit log views so that we can get started on this refactor after orgs is available as an experiment (and make sure to add this to the milestone!)~ added [here](https://github.com/coder/coder/issues/13958)

**Comment by code-asher** [comment]
I was going to add the organization ID to any resource where it can change, but after examination I think the organization ID never changes in any resource.  Which makes sense; I think we do not have any resources that can move from one organization to another?  I might need a sanity check on that though.  @Emyrk 

At best you could say it "changes" when you create/delete a resource (from nothing and to nothing) but the organization will already be showing in the audit log row for both those cases (next to IP/OS/Browser), so I am going to remove it from the diff on the few resources we do currently have it on for consistency (organization members and custom roles).

**Comment by Emyrk** [comment]
@code-asher you are correct, resources cannot move to a new organization.It's included as a top level field as you mentioned, so I agree it can be removed from the diff.

**Comment by code-asher** [comment]
Move audit page to `/deployment/audit`, redirect old audit link:

![Coder-Audit-All](https://github.com/user-attachments/assets/62501273-0bed-4703-8087-e3d08246345a)

And then orgs will also use `/deployment/audit`, but be pre-filled with `?q=organization:org-name`:

![Coder-Audit-Org](https://github.com/user-attachments/assets/b611cfb0-14f3-4cf7-9a32-6034cb4c4c3d)
