### ISSUE TITLE
Improve Go documentation usability

### ISSUE THREAD

**Issue by vapurrmaid** [coder/coder#1395]
## Overview

This ticket originally grew out of a question:  should we build a version of https://apidocs.coder.com/ for our `/coder/coder` v2 codebase?

We decided that Godoc gives us the benefits of Swagger and more, with more reliability. This is because there are less manual/duplicative pieces; the Godoc is autogenerated from the Go code (whereas Swagger is manual Go comments/annotations).

## Acceptance Criteria

We have a Godoc of our API/SDK (self-hosted until the repository is public, after which it can be freely hosted)

See breakout session comment here: https://github.com/coder/coder/issues/1395#issuecomment-1124249609

-----

- [x] https://github.com/coder/coder/issues/1398
- [ ] https://github.com/coder/coder/issues/1405
- [ ] https://github.com/coder/coder/issues/1565
