### ISSUE TITLE
Dynamic Parameters

### ISSUE THREAD

**Issue by stirby** [coder/coder#15231]
This is a collection of parameter improvements we'll be implementing as a single effort. 

## Background
Many customers (especially in the early stages of adoption) use a single generalized template for many teams. Since each team needs different regions, instance types and compute, administrators use [`coder_parameter`s](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/parameter) with docs to guide them on workspace configuration. Until they can make specified templates for each team, they heavily lean on parameters to enable this flexibility. However, our [existing parameter types](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/parameter#type) don’t allow admins to create a fully interactive wizard for the end user. More responsive parameters would enable template admins to design dynamic, branching flows for each team and slim down the documentation guidance. 

The new parameter system will enable the requested types below while maintaining the in-terraform configuration syntax. 

## Solution Components
- [ ] Parameter memory (autofill): https://github.com/coder/coder/issues/14757
- [ ] Conditional parameters: https://github.com/coder/coder/issues/11275
- [ ] Multi-select parameters: https://github.com/coder/coder/issues/5540
- [ ] Dropdown parameters: https://github.com/coder/coder/issues/10264
  - [ ] with search: https://github.com/coder/coder/issues/15038
- [ ] Secret parameters: https://github.com/coder/coder/issues/13472
- [ ] Dynamic parameters: https://github.com/coder/coder/issues/15652

### Other improvements
- [ ] https://github.com/coder/coder/issues/14483

**Comment by stirby** [comment]
We have delivered this in [Dynamic Parameters GA](https://coder.com/docs/admin/templates/extending-templates/dynamic-parameters as of [v2.25](https://github.com/coder/coder/releases/tag/v2.25.1). You can enable it in your template settings.

![Dynamic Parameters Settings](https://raw.githubusercontent.com/coder/coder/main/docs/images/admin/templates/extend-templates/dyn-params/dynamic-parameters-ga-settings.png)


Please see our [documentation](https://coder.com/docs/admin/templates/extending-templates/dynamic-parameters for more information!

You can also try conditional parameters on the [Parameter Playground](https://playground.coder.app/parameters).
