### ISSUE TITLE
Epic: Provisioner jobs and corresponding tags are confusing and difficult to troubleshoot ☂

### ISSUE THREAD

**Issue by bpmct** [coder/coder#15428]
## Background

Today, there are many scenarios where a workspace or template job gets stuck in an infinite `Pending` state, because there is no corresponding provisioner with the necessary tags. However, it is challenging for a user or admin to understand why. There are also some bugs and edge cases in this flow that we need to fix around the provisioner experience.

## Phase 0 (This week)

Improve our Helm charts and documentation on how to deploy provisioners and how tags work:
- [x] https://github.com/coder/coder/pull/15416
- [x] https://github.com/coder/coder/pull/15417

## Phase 1 (December 3 Release)

As an user, I need to understand why my workspace is stuck in a pending state and which tags are assigned to the job via clear UI warnings
- [ ] https://github.com/coder/coder/issues/15048

As an admin, I want to use the same provisioners for template imports as workspace builds when I use the `coder_workspace_tags` data source in my templates
- [ ] https://github.com/coder/coder/issues/15427

As an admin, I want consistent and predictable behaviors when I use `coder_workspace_tags` data source, and want clear warnings when it is being used incorrectly
- [ ] https://github.com/coder/coder/issues/15087

## Phase 2 (January 7 Release)

As an admin, I want to import starter templates and either A) see provisioner tags or B) have a guarantee it'll be imported to a generic provisioner
- [ ] https://github.com/coder/coder/issues/15426

As an admin, I want to be able to browse/delete/cancel provisioner jobs in the UI, especially ones that are stuck in pending
- [ ] https://github.com/coder/coder/issues/15084
- [ ] https://github.com/coder/coder/issues/15193

**Comment by SasSwart** [comment]
I'm babysitting this while Cian's on PTO.

**Comment by johnstcn** [comment]
Current status: https://github.com/coder/coder/issues/15048 is partially done and released in 2.18.
We're adding more visibility around workspace builds; this will end up in the January release (and possibly a later 2.18 patch).

**Comment by SasSwart** [comment]
> Current status: [#15048](https://github.com/coder/coder/issues/15048) is partially done and released in 2.18. We're adding more visibility around workspace builds; this will end up in the January release (and possibly a later 2.18 patch).

#15048 is now closed.

**Comment by johnstcn** [comment]
Closing this out as all the child issues have been resolved. Any other pending items as a result of those issues will be tracked separately.
