### ISSUE TITLE
Workspace apps support

### ISSUE THREAD

**Issue by misskniss** [coder/coder#257]
v2 workspaces need to support Dev URLs. For v2 community edition, a basic DevURL with private-only (local to the workspace and workspace owner) access is needed.

Advanced features with additional permissions and access levels, as well as wildcard support, will be part of paid Enterprise features. 

-----

- [x] https://github.com/coder/coder/issues/674
- [ ] https://github.com/coder/coder/issues/675
- [x] https://github.com/coder/coder/issues/676
