### ISSUE TITLE
SearchBarWithFilter improvement checklist

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#2608]
As I user, I want to be able to filter and search through my workspaces in the UI; however, I am confused when I come across the SearchBarWithFilter component. We should add/fix the following so I can use this component more intuitively:

**AC**
- [x] search should occur as a user types (right now, I have to finish typing and then refresh the page)
- [x] we should add active classes to the input/dropdown that mimic native styling so that it is visually clear something is happening when users type or select
- [ ] ~we should increase the contrast on the dropdown select options for better visibility into which option is selected~ we're not going to do this because it matches the other dropdowns
- [ ] ~we should display the current selected filter somewhere on the page so I know what the list is currently filtered on (maybe as a [badge](https://mui.com/material-ui/react-badge/))~ we're going to rely on the current design like Github
- [ ] ~we should add some sort of directive so users know how to search, e.g. search by name, or status or whatever~ we're going to rely on the current design like Github
- [x] we should get rid of this highlight on the search icon:
![Screen Shot 2022-06-27 at 11 20 47 AM](https://user-images.githubusercontent.com/19142439/176014861-c3a9c40b-b450-4d0f-90db-e06da9d14883.png)
- [x] we should add some basic unit tests for this component
