### ISSUE TITLE
Web Terminal for Workspaces

### ISSUE THREAD

**Issue by misskniss** [coder/coder#265]
Our web terminal needs to work with V2 as it does with V1. 

-----

- [x]  Create a websocket to proxy an SSH shell - BETA
https://github.com/coder/coder/issues/759
- [x] Creating the web terminal page (or vendorize xterm) - BETA
https://github.com/coder/coder/issues/760
- [x] Webpack todos - BETA
https://github.com/coder/coder/issues/761

-----

⚠️ _The initial issues filed under this epic may not be the full representation of the work._
- _Feel free to create/modify issues._
- _Please add points and tag new issues with the epic they belong to_ 
- _Please let EM or PM know if there is a reason something should NOT be in this milestone/epic **IF** it changes the intent of the Community MVP delivery items in the [Scoping doc](https://www.notion.so/coderhq/Workspaces-v2-MVP-Scope-95932c6f77944bb2af516dab1411781d) so we can adjust accordingly or discuss_
