### ISSUE TITLE
July Roadmap

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#3042]
This is our first time doing this and it’s starting late in the month, so it’s a shot in the dark as to how much will get done. For the August roadmap, we will be having a planning session in Discord.

- Developers are responsible for their sections. Feel free to change the description and adjust the attached issues.
- Owners are referenced for large tasks to see available work at a quick glance. GitHub assignees are still used!
- Don’t allocate 100% of your time on roadmap items. We need to ad-hoc respond to and fix customer or community issues.

### ✏️ template.yaml

Template name, description, and schedule are not stored in a template version. There is no way to source control these properties, and it’s likely to become problematic as we create more.

https://github.com/coder/coder/issues/2987 👋 you could own this

### 📜 Resource Metadata + Secrets

Developers want to see additional metadata about resources in Coder. This could be an instance type, the number of cores an instance has, or a link to the cloud resource itself (say in a GCP dashboard).

https://github.com/coder/coder/issues/2989 👋 you could own this

### 📡 Tailscale Networking

Users have been reporting connection issues with WebRTC, and it’s been difficult to debug. We’ve had to build a lot of networking code that isn’t fun or easy to maintain. We can replace our WebRTC networking with Tailscale to remove ~3000 lines of networking code, and fix a bunch of issues for our users!

https://github.com/coder/coder/issues/2779 @kylecarbs

### 🌁 JetBrains Gateway

We lack docs for Gateway right now, which could give the perception that it doesn’t work with Coder. Ideally, someone that uses Gateway daily with Coder takes this (or someone that wants to, but there are too many bugs).

- Verify that Gateway works on the latest EAP when connecting to a Linux Coder agent. Working versions should be documented with a “last updated at” alongside the version. 👋 you could own this
- Document the limitation of Gateway with non-Linux Coder agents (this is a limitation on their part, see: [https://youtrack.jetbrains.com/issue/CWM-3653/Remote-development-host-should-be-available-on-macOS-and-Windows](https://youtrack.jetbrains.com/issue/CWM-3653/Remote-development-host-should-be-available-on-macOS-and-Windows)). 👋 you could own this

### 🚛 Nice to Haves

Don’t feel the need to grab a big task every cycle. Small fixes add up! This provides a sorted list of issues to fix that we’ll focus on, but won’t capture all work completed in a cycle (hover over issue numbers to get some more detail):

- [ ]  https://github.com/coder/coder/issues/3005
- [ ]  https://github.com/coder/coder/issues/3025
- [ ]  https://github.com/coder/coder/issues/2764
- [ ]  https://github.com/coder/coder/issues/2960
- [ ]  https://github.com/coder/coder/issues/2752
- [ ]  https://github.com/coder/coder/issues/2970
- [ ]  https://github.com/coder/coder/issues/3000
- [ ]  https://github.com/coder/coder/issues/3024
- [ ]  https://github.com/coder/coder/issues/2714
- [ ]  https://github.com/coder/coder/issues/1369
- [ ]  https://github.com/coder/coder/issues/2836
- [ ]  https://github.com/coder/coder/issues/2146
- [ ]  https://github.com/coder/coder/issues/3013
- [ ]  https://github.com/coder/coder/issues/2966
- [ ]  https://github.com/coder/coder/issues/2842
- [ ]  https://github.com/coder/coder/issues/2840
- [ ]  https://github.com/coder/coder/issues/2969
- [ ]  https://github.com/coder/coder/issues/3012
- [ ]  https://github.com/coder/coder/issues/3031
- [ ]  https://github.com/coder/coder/issues/2815

**Comment by mark-theshark** [comment]
@kylecarbs Health check for IDE icons ensures a good end-user experience. If the `startup_script` is still running, a user can click an IDE and it will fail.  Health check for IDE icons https://github.com/coder/coder/issues/2662

**Comment by kylecarbs** [comment]
Hmm, fair point. I wonder if we should adjust `startup_script` to potentially block the starting of an agent...? Seems like it could be a better approach.

**Comment by bpmct** [comment]
Some high-priority candidates for July or August:

- #2267
- #802 / #2660
- #696 
- #1763
- #1624
- #2760

Nice to have
- #2659
- #2262 / #2221 (better splash for marketing/demos)
- #3033
- #2918
- #3054

**Comment by kylecarbs** [comment]
We're taking out template.yaml and moving Helm chart into July @bpmct. #1763 will also be added. The rest will be in August.

**Comment by kylecarbs** [comment]
@bpmct I think you can swap in #2659, #2262, and #2221 for July. Just take some lesser important issues out of the nice to have (chefs choice).

**Comment by ammario** [comment]
For posterity, #2987 was added back since @sreya already began work.

Can we slot in https://github.com/coder/coder/issues/2135 since it's low effort and has been requested numerous times?

**Comment by ammario** [comment]
This is another severe bug https://github.com/coder/coder/issues/2960 related to workspace scheduling. I think it's more important than most of the current Nice to Haves.
