### ISSUE TITLE
VS Code Extension

### ISSUE THREAD

**Issue by ammario** [coder/coder#3597]
As a user, I want to start and connect to my Coder workspace without opening the dashboard or using the CLI.

A VS Code extension has a slight comparative advantage over the workflow of `coder start ... && coder config-ssh`, but it is helpful for marketing as people will discover Coder through the extension marketplace.

We have a WIP extension. [You can try it here](https://marketplace.visualstudio.com/items?itemName=coder.coder-remote)

## TODO

- [ ] New version with fixed reconnecting bug & initial connection bug fixes
- [ ] Open-sourced with filled-in README
- [ ] Button from the dashboard to Open into VS Code

**Comment by bpmct** [comment]
A VS Code extension can also be used to more accurately determine activity. #2995

**Comment by bpmct** [comment]
Some other interesting use cases:

- see latency for workspace
- access and start workspaces without the dashboard

**Comment by mafredri** [comment]
An additional use-case came up in #4927:

- Surface workspace status and issues via in-VSCode notifications (examples: outdated workspace, cli version mismatch, license issues)

**Comment by kylecarbs** [comment]
This is completed! Checkout https://github.com/coder/vscode-coder
