### ISSUE TITLE
Organization Support

### ISSUE THREAD

**Issue by misskniss** [coder/coder#479]
## Breakout Discussion
March 17, 2022
[RFC](https://www.notion.so/coderhq/Workspaces-V2-User-Organization-Management-827ed8bbd1f5490dbd01ddd65d112dce)

-----

- [x] https://github.com/coder/coder/issues/197
- [x] https://github.com/coder/coder/issues/664
- [x] https://github.com/coder/coder/issues/663
- [x] https://github.com/coder/coder/issues/665
- [x] https://github.com/coder/coder/issues/681
