### ISSUE TITLE
Windows Experience

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#5051]
This is an epic that tracks enhancements for windows.

## High

- [x] https://github.com/coder/coder/issues/5050
- [x] https://github.com/coder/coder/issues/5049
- [x] https://github.com/coder/coder/issues/3714

## Medium

- [ ] https://github.com/coder/coder/issues/5048
- [x] https://github.com/coder/coder/issues/4226
- [ ] https://github.com/coder/coder/issues/4870
- [x] https://github.com/coder/coder/issues/4869
- [ ] https://github.com/coder/coder/issues/2106
- [ ] https://github.com/coder/coder/issues/4007
- [ ] Integrate https://github.com/coder/coder/pull/4719
