### ISSUE TITLE
Scheduling (auto-start, auto-stop) Epic

### ISSUE THREAD

**Issue by presleyp** [coder/coder#5150]
## Bugs

- [x] Fix disabling of auto-stop #5146
- [x] Fix incrementer on workspace page #5037
- [x] Fix disabling of auto-start #5149
- [x] Fix auto-stop logging #5183 
- [x] Fix template schedule form #5064
- [x] Change behavior of auto-stop updates to be less confusing (probably should kick in immediately but with a confirmation dialog if it would mean immediate shutdown) #5080 
- [x] Fix incrementer again #5354 
- [x] Fix default upon enabling auto-stop #5154 

## Enhancements (need discussion)

- [ ] #2733 
- [ ] #3630 
- [x] #2279
- [ ] #3380

**Comment by matifali** [comment]
May be you can also add #2733

**Comment by dcarrion87** [comment]
Are some of these likely to make it into release or do all of them need to be completed first? We're finding off a number of complaints from users about auto stop disabling not working correctly. I.e. https://github.com/coder/coder/issues/5183

**Comment by dcarrion87** [comment]
@presleyp just realised I linked the wrong one 🤦 . I meant this one: https://github.com/coder/coder/issues/5146

I might just hold off as looks like there's some regressions happening in latest releases.

**Comment by presleyp** [comment]
@dcarrion87 Yes, it was released in https://github.com/coder/coder/releases/tag/v0.13.0

**Comment by dcarrion87** [comment]
@presleyp was that under this one?

https://github.com/coder/coder/commit/2e3db274f103505afddfdce460ab917b85d8d60a fix: send auto start/stop api calls only when changed (https://github.com/coder/coder/pull/5184)

Or a different one?

**Comment by presleyp** [comment]
@dcarrion87 #5151 - you can find it by going to #5146 and seeing the number of the PR that fixed the issue.

**Comment by dcarrion87** [comment]
OK thanks I'll do some testing.

**Comment by bpmct** [comment]
Going to close this for now in favor of individual issues.
