### ISSUE TITLE
Admin Settings Support 

### ISSUE THREAD

**Issue by misskniss** [coder/coder#589]
As an admin, I want an Admin page that collects all the configurations and settings I am allowed for my workspaces, etc. 

-----

- [ ] https://github.com/coder/coder/issues/796
- [ ] https://github.com/coder/coder/issues/797
- [x] https://github.com/coder/coder/issues/798
- [x] https://github.com/coder/coder/issues/818

-----

## Discussion Notes

Note, there is a little bit of conflation going on here between this being a page of all the things an admin can do and a page of workspace administration actions that has varying visibility based on role. We may want to call this "Workspace Administration" and allow the features on this page to show/hide based on the user's role. 

Items for Beta include[ these items](https://www.notion.so/coderhq/V1-List-of-Pages-Sections-Functionality-4839e9baacd94df4aac22a68d77afe44#fb9ccc44f56948d297259318596b8de8) (🐣) from V1
Items for Community MVP include [these items](https://www.notion.so/coderhq/V1-List-of-Pages-Sections-Functionality-4839e9baacd94df4aac22a68d77afe44#fb9ccc44f56948d297259318596b8de8) (🐥) from V1

This is a nav option under the "Manage" nav menu that is only present for Admins/Site Managers. Nested under "Manage" is an option called "Admin". We will be renaming "Manage" to "Admin" and renaming "Admin" to "Settings".

The following items should live under the "Settings" menu:
Rename this to "Settings" - Done
Do we have UI representative issues for the following?

- #921
- Access URL does not need a UI but needs coverage. https://github.com/coder/coder/issues/788
- DevURL access levels ENT https://github.com/coder/coder/issues/787
- Authentication - this is the OIDC set-up page. This will be needed for Community https://github.com/coder/coder/issues/789
- Security - This is not needed 
- Git OAuth - This is needed for Community https://github.com/coder/coder/issues/791
- License - Needed for Community https://github.com/coder/coder/issues/793
- Appearance - This is not needed until Enterprise https://github.com/coder/coder/issues/794
- Telemetry - UI Not needed 
- Dormancy - Needed for enterprise https://github.com/coder/coder/issues/795
- Templates - Not needed

Example UI:
![Admin Pages.png](https://images.zenhubusercontent.com/588b7bd751aa2c305772f431/056e71ac-3b1f-497a-81c3-d3a71cc06b7a)

-----

⚠️ _The initial issues filed under this epic may not be the full representation of the work._
- _Feel free to create/modify issues._
- _Please add points and tag new issues with the epic they belong to_ 
- _Please let EM or PM know if there is a reason something should NOT be in this milestone/epic **IF** it changes the intent of the Community MVP delivery items in the [Scoping doc](https://www.notion.so/coderhq/Workspaces-v2-MVP-Scope-95932c6f77944bb2af516dab1411781d) so we can adjust accordingly or discuss_
