### ISSUE TITLE
User Preferences Support

### ISSUE THREAD

**Issue by misskniss** [coder/coder#590]
As a user, I would like to have some control over preferences like my avatar, light/dark theme, etc so I can personalize my account. 
Preferences features for the Community MVP from V1 include [these items ](https://www.notion.so/coderhq/V1-List-of-Pages-Sections-Functionality-4839e9baacd94df4aac22a68d77afe44#a9b3cfc119fe43db8f210312cde34dfd)( 🐥 )

Preference features for Enterprise MVP from V1 include [these Items](https://www.notion.so/coderhq/V1-List-of-Pages-Sections-Functionality-4839e9baacd94df4aac22a68d77afe44#a9b3cfc119fe43db8f210312cde34dfd) ( 🌲 )

The following will not be include in the preferences page going forward: 
- Appearance  (default to only dark mode)
- Auto On/Off ( will be located elsewhere in the UI)

<img width="445" alt="User Preferences Options in V1" src="https://user-images.githubusercontent.com/2394436/160980109-78d53f33-1ffd-4bcd-9c04-37607020472d.png">

-----

- [x] https://github.com/coder/coder/issues/814
- [x] https://github.com/coder/coder/issues/746
- [x] https://github.com/coder/coder/issues/747
- [x] https://github.com/coder/coder/issues/749
- [x] https://github.com/coder/coder/issues/748
- [x] https://github.com/coder/coder/issues/750

**Comment by misskniss** [comment]
Closing this. No open tasks.
