### ISSUE TITLE
Organizations - Enterprise

### ISSUE THREAD

**Issue by tjcran** [coder/coder#665]
- [x] https://github.com/coder/coder/issues/617
- [x] https://github.com/coder/coder/issues/604
- [x] https://github.com/coder/coder/issues/618
- [x] https://github.com/coder/coder/issues/619
- [x] https://github.com/coder/coder/issues/686
- [x] #973
