### ISSUE TITLE
Resilient GPG forwarding via `coder config-ssh`

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6672]
## Problem

You cannot do GPG forwarding with `coder config-ssh` right now (e.g. RemoteFoward) is flaky. [Internal thread](https://codercom.slack.com/archives/C014JH42DBJ/p1679308285624239)

## Tasks

- [x] Fix: GPG forwarding via `RemoteForward` only works once as it does not properly close. Users have to restart their workspaces to forward again
- [x] Improve resiliency (avoid having to restart gpg agent in workspace, on local machine, etc). 
  - `coder ssh --forward-gpg` is a much more stable option currently  
- [x] Support some way to enable GPG forwarding deployment-wide with config-ssh defaults #6613
