### ISSUE TITLE
Users - Enterprise MVP

### ISSUE THREAD

**Issue by misskniss** [coder/coder#668]
- [x] https://github.com/coder/coder/issues/593
- [x] https://github.com/coder/coder/issues/595
- [x] https://github.com/coder/coder/issues/599
- [x] https://github.com/coder/coder/issues/600
- [x] https://github.com/coder/coder/issues/604
- [x] https://github.com/coder/coder/issues/605
- [ ] #613 
- [ ] #614 
- [ ] https://github.com/coder/coder/issues/667
- [ ] #677 
- [ ] https://github.com/coder/coder/issues/979
