### ISSUE TITLE
RBAC - Community MVP

### ISSUE THREAD

**Issue by tjcran** [coder/coder#671]
- [x] https://github.com/coder/coder/issues/52
- [x] https://github.com/coder/coder/issues/607
- [x] https://github.com/coder/coder/issues/1371
- [x] #1074 
- [x] https://github.com/coder/coder/issues/717
- [x] https://github.com/coder/coder/issues/724

**Comment by misskniss** [comment]
Closing this. All tasks closed.
