### ISSUE TITLE
Users - Post MVP

### ISSUE THREAD

**Issue by misskniss** [coder/coder#673]
- [ ] https://github.com/coder/coder/issues/597
- [ ] https://github.com/coder/coder/issues/603
- [ ] https://github.com/coder/coder/issues/606
- [ ] https://github.com/coder/coder/issues/608
- [ ] https://github.com/coder/coder/issues/609
- [ ] https://github.com/coder/coder/issues/610
- [ ] https://github.com/coder/coder/issues/611
