### ISSUE TITLE
Workspaces - CRUD

### ISSUE THREAD

**Issue by tjcran** [coder/coder#678]
Figma: https://www.figma.com/file/TAJTcLDkMTgXLszIZN2TZI/v1-vs-v2?node-id=0%3A1

As a user I want the ability to create, read, update and delete a workspace. 

-----

- [x] https://github.com/coder/coder/issues/56
- [x] https://github.com/coder/coder/issues/67
- [x] https://github.com/coder/coder/issues/211
- [x] https://github.com/coder/coder/issues/1034
- [x] https://github.com/coder/coder/issues/235
- [x] https://github.com/coder/coder/issues/1033
- [x] https://github.com/coder/coder/issues/236
- [x] https://github.com/coder/coder/issues/769
- [x] https://github.com/coder/coder/issues/770
- [x] https://github.com/coder/coder/issues/1032
- [x] https://github.com/coder/coder/issues/766
- [x] #767 
- [x] https://github.com/coder/coder/issues/801
- [x] https://github.com/coder/coder/issues/768
- [x] https://github.com/coder/coder/issues/233
- [x] #1031 

-----

<img width="1229" alt="Workspaces Page from V1" src="https://user-images.githubusercontent.com/2394436/160305418-e2fcb7a9-9a5f-4d73-a38a-89b70b4dfdb2.png">

## Creating a new workspace
Needed inputs depend on project being used. @kylecarbs and @presleyp @tjcran  to sync up on what this means for building out the frontend. 
Frontend:  BETA
- Name
- Project ID
- Project Params?
- User params?
- Drop down selector for region?

CLI / API: Is Complete

## Viewing a list of workspaces
- Workspaces table - BETA
- All row items per workspace  - BETA

## Editing a workspace - BETA
See the admin page layout as an example for editing and viewing Workspace details
- Identify what would be "editable" items - add an edit icon next to these fields OR use a dialog or modal from an 'Edit' action in an action menu - BETA
- Viewing parameters for a workspace - use the github model to create hierarchy - BETA
- Make create and edit forms possible by parsing the parameters.

## Deleting a workspace - BETA

April Discussion on Workspace details: 
<img width="1423" alt="Workspace Details Page for Community MVP" src="https://user-images.githubusercontent.com/2394436/163598836-e72be9e9-d8f6-42b4-8638-785729bb6714.png">

**Comment by misskniss** [comment]
Closing this. Tasks complete.
