### ISSUE TITLE
Audit Log - Enterprise MVP

### ISSUE THREAD

**Issue by tjcran** [coder/coder#684]
- [x] https://github.com/coder/coder/issues/473
- [x] https://github.com/coder/coder/issues/474
- [x] https://github.com/coder/coder/issues/468
- [x] https://github.com/coder/coder/issues/471
- [x] https://github.com/coder/coder/issues/472
- [x] https://github.com/coder/coder/issues/475
