### ISSUE TITLE
AuthN / OIDC 

### ISSUE THREAD

**Issue by misskniss** [coder/coder#695]
These are the items we identify as needed in the Enterprise MVP as wither paid feature or additional Community features. 

-----

- [x] https://github.com/coder/coder/issues/820
- [x] #789
- [x] https://github.com/coder/coder/issues/790
- [x] https://github.com/coder/coder/issues/792
- [ ] https://github.com/coder/coder/issues/696

**Comment by misskniss** [comment]
Added this epic to collect the OIDC work for August.
