### ISSUE TITLE
Deprecation plan for legacy parameters

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7452]
While we've communicated via docs that we plan on deprecating legacy parameters by the end of April, not all of our users read our docs or changelog.

While we're communicating this to our customers and prospects, let's add a 2-week buffer window while we add a banner on workspaces and templates

> This template uses legacy parameters which will be deprecated in the next Coder release. Learn how to migrate in [our documentation](#)

Of course, we will add this to our changelog when we deprecate too, but this is one additional measure to avoid data loss.

---

After entirely moving the code, we should still keep some detection logic (perhaps for 6 months) that explains that they are not supported and prevent builds. This would be much better than some random error.

**Comment by mtojek** [comment]
Battle plan:

- [ ] expose `warnings[]` property in `/api/v2/templateversions/<template-version>` 
- [ ] export `template_version_warnings[]` property in `/api/v2/templateversion/<template-version>`
- [ ] site: when any user opens the template page for a template with legacy params, site will show a banner
- [ ] site: when any user opens the workspace page for a workpace using a template with legacy params, site will show a banner

**Comment by matifali** [comment]
Oh this planning for the deprecation is itself a huge task.

**Comment by mtojek** [comment]
Battle plan (agreed during the Weekly meeting last Monday):
- [ ] Migrate, delete old workspaces and templates using legacy parameters
- [ ] Remove legacy parameters logic from code (blocked by: https://github.com/coder/coder/pull/7541)
- [ ] Leave detection logic to block adding templates with legacy parameters.
