### ISSUE TITLE
Scale testing: umbrella issue

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#7601]
This is just a placeholder issue for work related to load testing.

- [ ] https://github.com/coder/coder/issues/7596
- [ ] https://github.com/coder/coder/issues/7597
- [ ] https://github.com/coder/coder/issues/7598
- [ ] https://github.com/coder/coder/issues/7599
- [ ] https://github.com/coder/coder/issues/7600
