### ISSUE TITLE
dev: Improve development experience 

### ISSUE THREAD

**Issue by matifali** [coder/coder#7676]
## Context 

~I tried using `nix-shell` in the context of #4854 but could not get a usable development environment~. I also tried using the `.devcontainer`, and it also failed to provide a usable development environment.

Currently, we have **three** different approaches to creating a development environment to build Coder.

1. `nix-shell`
2. `.devcontainer`
3. `dogfood` template

## Problem

1. ~`nix-shell`~ and `.devcontainer` are practically unusable.
2. All three of the approaches do not align in terms of build tools versions.

## Suggested Solution

- [x]  Fix `nix-shell` #4854 or remove support
- [x]  Fix `.devcontainer` #7591 
- [x]  Align the `dogfood` template with '.devcontainer' #5211
- [ ]  Eventually, update the `dogfood` template to use `.devcontainer` for provisioning of build/dev environment. (@johnstcn suggestion) (should be possible with [`envbuilder`]( https://github.com/coder/envbuilder))

cc: @johnstcn @ammario @kylecarbs @bpmct

**Comment by MrPeacockNLB** [comment]
hmn... I use a coder workspace to develop for coder. Our dev environment is currently based on manjaro linux. I' also installed nix-shell. After so hints from @BrunoQuaresma I was able to build coder. First I thought there were some tools missing too, but this wsa my fault as I've forgotten to run nix-shell in the new terminal.
