### ISSUE TITLE
CLI Experience - Community MVP

### ISSUE THREAD

**Issue by tjcran** [coder/coder#777]
- [x] https://github.com/coder/coder/issues/491
- [x] https://github.com/coder/coder/issues/493
- [x] #826 
- [x] #829 
- [x] https://github.com/coder/coder/issues/1173
- [x] https://github.com/coder/coder/issues/1204
- [x] https://github.com/coder/coder/issues/1205
- [x] https://github.com/coder/coder/issues/1226
- [x] #1291 
- [x] https://github.com/coder/coder/issues/828
- [x] https://github.com/coder/coder/issues/1233
- [x] #1377 
- [x] https://github.com/coder/coder/issues/1606
- [x] #495 
- [x] #917 
- [x] https://github.com/coder/coder/issues/1175
- [x] #831

**Comment by misskniss** [comment]
Closing this. Tasks complete. moved the recent bug to the touch ups epic.
