### ISSUE TITLE
Admin Settings  - Enterprise MVP

### ISSUE THREAD

**Issue by tjcran** [coder/coder#798]
- [x] https://github.com/coder/coder/issues/787
- [x] https://github.com/coder/coder/issues/789
- [x] https://github.com/coder/coder/issues/793
- [x] https://github.com/coder/coder/issues/794
- [x] https://github.com/coder/coder/issues/795
