### ISSUE TITLE
Single Tailnet GA

### ISSUE THREAD

**Issue by coadler** [coder/coder#8507]
https://github.com/coder/coder/pull/8176 was merged behind an experiment. A couple things need to happen before removing the experiment.

- [x] https://github.com/coder/coder/issues/8508
- [x] https://github.com/coder/coder/issues/8509
- [x] https://github.com/coder/coder/issues/8510
- [ ] https://github.com/coder/coder/issues/10391
- [ ] Move out of experimental

**Comment by coadler** [comment]
This has been shipped.
