### ISSUE TITLE
add a Full Name to accounts page

### ISSUE THREAD

**Issue by matifali** [coder/coder#9883]
## Context

Currently, we only have `Username` and `Email`, I would like also to have `name` that can be set to any name by the user. For example, I want to set it to "Muhammad Atif Ali" and be accessed via `data.coder_workspace.me.owner_name`

![image](https://github.com/coder/coder/assets/10648092/8e7d1176-c087-4f63-a960-601c1329d5ce)

## ToDo

- [x] https://github.com/coder/terraform-provider-coder/pull/181 Add to [`coder_workspace`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace) data in terraform provider as `data.coder_workspace.me.owner_name`
- [x] https://github.com/coder/coder/pull/11639 Add to backend/database
- [ ] https://github.com/coder/coder/pull/11683 Add to accounts page as `Name` settable to "First Name, Last Name"

## Motivation

This will allow us to set the full name of the developers as the `user.name` property for our git-config module. e.g., `git config user.name "${data.coder_workspace.me.owner_name}"`

cc: @kylecarbs, @bpmct and @ammario for comments

**Comment by ammario** [comment]
👍🏽 seems logical to me.

**Comment by johnstcn** [comment]
Note: I wouldn't bother breaking up the first name / last name fields in the UI.
See: https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by mtojek** [comment]
Yup, a [single name field](https://github.com/coder/coder/pull/11639) instead will be safer 👍
